dist: trusty
language: java
sudo: required
os: linux
jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2"

services: postgresql

before_script:
  - cd backend
  - chmod +x mvnw
  - psql -c 'create database "ComprasEnCasa";' -U postgres