dist: trusty
language: java
sudo: required
os: linux
jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2"

services: postgresql

before_cache:
  - rm -rf $HOME/.m2/repository/unq/ar/edu/dessap/grupol

before_script:
  - cd backend
  - chmod +x mvnw
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - psql -c 'create database "ComprasEnCasa";' -U postgres

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r target/jacoco/jacoco.xml